[project]
name = "flask-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "siddu", email = "siddusiddu0149@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask",
    "pymongo",
    "flask-jwt-extended",
    "werkzeug"
]

[project.scripts]
flask-blog = "flask_blog:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"